name: Not So Khoi
favicon: null
layout_spectrum: 0.25802
typography_spectrum: 0.31215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0a3b49'
    - '#2995b0'
    - '#48c6e6'
    - '#fefdfc'
  brandStrength: 0.4832880462054163
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
