name: notsokhoi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0000'
    - '#302130'
    - '#ffffe5'
    - '#c4b3ad'
    - '#8b8b90'
  brandStrength: 0.4832880462054163
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
