name: notsokhoi
favicon: null
layout_spectrum: 0.9734877191949636
typography_spectrum: 0.6708519691601396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4832880462054163
  lightness: 0.09610698861069977
  saturation: 0.16737888869829476
  rhythmicContrast: 0.4456340866163373
purpose: []
